from fpdf import FPDF
from datetime import datetime
import io

class AccreditationReport(FPDF):
    def header(self):
        self.set_fill_color(31, 78, 121)
        self.rect(0, 0, 210, 25, 'F')
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(255, 255, 255)
        self.set_y(8)
        self.cell(0, 8, 'NUC ACCREDITATION MANAGEMENT SYSTEM', align='C')
        self.ln(5)
        self.set_font('Helvetica', '', 9)
        self.cell(0, 5, 'Programme Accreditation Readiness Report', align='C')
        self.set_text_color(0, 0, 0)
        self.ln(10)

    def footer(self):
        self.set_y(-20)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(150, 150, 150)
        self.multi_cell(
            0, 4,
            f'This report was automatically generated by the NUC Accreditation '
            f'Management System. It is intended for internal use only and does '
            f'not constitute official NUC accreditation.',
            align='C'
        )
        self.set_text_color(0, 0, 0)


def generate_pdf_report(report_data):
    pdf = AccreditationReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Programme Info Section ──────────────────────────
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(245, 249, 252)
    pdf.set_draw_color(200, 200, 200)

    pdf.cell(0, 8, '', ln=True)  # spacer

    info = [
        ('Programme', report_data['programme']),
        ('Department', report_data['department']),
        ('Faculty', report_data['faculty']),
        ('Current Status', report_data['status']),
        ('Report Generated', report_data['generated_at']),
    ]

    for label, value in info:
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_text_color(31, 78, 121)
        pdf.cell(45, 7, f'{label}:', border=0)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, str(value), border=0, ln=True)

    pdf.ln(4)

    # ── Horizontal line ─────────────────────────────────
    pdf.set_draw_color(44, 95, 138)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # ── Verdict Banner ───────────────────────────────────
    verdict = report_data['verdict']
    score = report_data['score']

    if verdict == 'READY':
        r, g, b = 212, 237, 218
        tr, tg, tb = 30, 126, 52
    elif verdict == 'PARTIALLY READY':
        r, g, b = 255, 243, 205
        tr, tg, tb = 133, 100, 4
    else:
        r, g, b = 248, 215, 218
        tr, tg, tb = 114, 28, 36

    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(tr, tg, tb)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(
        0, 12,
        f'  OVERALL VERDICT: {verdict}   |   Readiness Score: {score}%  '
        f'({report_data["passed"]}/{report_data["total"]} requirements met)',
        border=1, ln=True, fill=True
    )
    pdf.ln(2)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 5, report_data['verdict_message'])
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Requirements Table ───────────────────────────────
    pdf.set_draw_color(44, 95, 138)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(31, 78, 121)
    pdf.cell(0, 8, 'Detailed Requirements Assessment', ln=True)
    pdf.ln(2)

    # Table header
    pdf.set_fill_color(31, 78, 121)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(60, 8, 'Requirement', border=1, fill=True)
    pdf.cell(28, 8, 'Status', border=1, fill=True, align='C')
    pdf.cell(102, 8, 'Detail', border=1, fill=True, ln=True)

    # Table rows
    for i, check in enumerate(report_data['checks']):
        status = check['status']

        if status == 'PASS':
            sr, sg, sb = 212, 237, 218
            tr2, tg2, tb2 = 30, 126, 52
            symbol = 'PASS'
        elif status == 'WARNING':
            sr, sg, sb = 255, 243, 205
            tr2, tg2, tb2 = 133, 100, 4
            symbol = 'WARNING'
        else:
            sr, sg, sb = 248, 215, 218
            tr2, tg2, tb2 = 114, 28, 36
            symbol = 'FAIL'

        row_fill = (245, 249, 252) if i % 2 == 0 else (255, 255, 255)

        # Calculate row height based on detail text length
        detail = check['detail']
        row_h = 7

        pdf.set_fill_color(*row_fill)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', '', 8)

        y_before = pdf.get_y()
        x_before = pdf.get_x()

        pdf.cell(60, row_h, check['category'], border=1, fill=True)

        pdf.set_fill_color(sr, sg, sb)
        pdf.set_text_color(tr2, tg2, tb2)
        pdf.set_font('Helvetica', 'B', 8)
        pdf.cell(28, row_h, symbol, border=1, fill=True, align='C')

        pdf.set_fill_color(*row_fill)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', '', 8)
        pdf.cell(102, row_h, detail[:70] + ('...' if len(detail) > 70 else ''), border=1, fill=True, ln=True)

    pdf.ln(5)

    # ── Recommendations Section ──────────────────────────
    recommendations = [c for c in report_data['checks'] if c.get('recommendation')]

    if recommendations:
        pdf.set_draw_color(44, 95, 138)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(31, 78, 121)
        pdf.cell(0, 8, 'Recommendations for Accreditation Readiness', ln=True)
        pdf.ln(2)

        for i, rec in enumerate(recommendations, start=1):
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_text_color(31, 78, 121)
            pdf.cell(0, 6, f'{i}. {rec["category"]}', ln=True)
            pdf.set_font('Helvetica', '', 9)
            pdf.set_text_color(60, 60, 60)
            pdf.set_x(15)
            pdf.multi_cell(0, 5, rec['recommendation'])
            pdf.ln(1)

    # ── Return as bytes ──────────────────────────────────
    pdf.set_text_color(0, 0, 0)
    # request string/bytes output from FPDF in memory
    output = pdf.output(dest='S')
    # fpdf (original) may return a str, fpdf2 returns bytes — normalize to bytes
    if isinstance(output, str):
        output = output.encode('latin-1')
    return io.BytesIO(output)