from rest_framework import serializers
from .models import Document


class DocumentSerializer(serializers.ModelSerializer):
    # frontend sends `file_name` — map it to the model's `title` field
    file_name = serializers.CharField(source='title', write_only=True, required=False)
    # Accept arbitrary frontend keys for category and map them in
    # `validate_category`. This prevents the autogenerated ChoiceField from
    # rejecting frontend keys before our mapping runs.
    category = serializers.CharField(required=False)

    # Map frontend category keys (used in the React app) to the model's
    # Category values. Unknown keys fall back to OTHER so uploads don't fail
    # validation when the frontend uses a richer set of categories.
    CATEGORY_MAP = {
        'marking_schemes': 'OTHER',
        'lesson_notes': 'CURRICULUM',
        'ca_records': 'OTHER',
        'examiner_reports': 'OTHER',
        'staff_files': 'STAFF_LIST',
        'student_files': 'OTHER',
        'qa_reports': 'OTHER',
        'research_evidence': 'OTHER',
        'question_papers': 'OTHER',
        'other': 'OTHER',
    }

    class Meta:
        model = Document
        fields = '__all__'
        read_only_fields = ['uploaded_by', 'uploaded_at']
        extra_kwargs = {
            'title': {'required': False},
            'programme': {'required': False},
        }

    def validate_category(self, value):
        """
        Accept either the model's canonical choice value (e.g. 'STAFF_LIST') or
        the frontend key (e.g. 'staff_files'). Map frontend keys to the model
        values. Unknown keys default to 'OTHER'.
        """
        # If frontend accidentally sends the model value already, accept it
        model_values = {v for v, _ in Document.Category.choices}
        if value in model_values:
            return value

        mapped = self.CATEGORY_MAP.get(value)
        if mapped:
            return mapped

        # Fallback
        return Document.Category.OTHER