# Generated by Django 6.0.5 on 2026-06-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('FORWARDED_TO_NUC', 'Forwarded to NUC'), ('ACCREDITED', 'Accredited'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
