# Generated by hand for CI/test purposes
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_alter_programme_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DOWNLOAD', 'Download'), ('VIEW', 'View')], max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_audits', to='programmes.programme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
